### ISSUE TITLE
Feature request: self-signed certificate support and basic HTTP authentication

### ISSUE THREAD

**Issue by uidzero** [substack/wsnc#2]
It appears wsnc may support basic HTTP authentication already. I didn't have a working websocket URL to test with. However, it definitely errors on a self signed cert:

```
$ ./cmd.js  wss://user:pass@host
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)
```

**Comment by joeireland** [comment]
To ignore self-signed cert errors run the following command before executing wsnc:

export NODE_TLS_REJECT_UNAUTHORIZED="0"

**Comment by joeireland** [comment]
An alternative would be that this pull request - https://github.com/substack/wsnc/pull/5 be merged to master. That pull request includes support for ignoring SSL self-signed cert errors by specifying the -i command-line parameter.
